### ISSUE TITLE
Optionally fail if user/key not given

### ISSUE THREAD

**Issue by tomasbjerre** [bintray/gradle-bintray-plugin#204]
I have a shared build script like:
```
...
bintray {
 user = System.getenv('BINTRAY_USER')
 key = System.getenv('BINTRAY_KEY')
...
```

I spent about an hour troubleshooting why I suddenly was unable to release from my laptop. After a while, when running with `-i`, I saw a small info log about not running `bintrayUpload` because no user was specified.

If I could set a property that says the plugin should fail, instead of just ignoring the missing property, that would have med me realize this much faster. Or always fail if the property is not set, unless there is a use case where someone would want to run without a user.

Same thing with `mavenCentralSync`. If someone configures `sync = true` but configures no user/password, I think there should be an error.

**Comment by vgaidarji** [comment]
Same happened to me, build was always successful but `bintrayUpload` (1.8.0 plugin version) did nothing. I had to dig deeper with `./gradlew bintrayUpload --debug` to actually find that `user/key` were not passed correctly to `bintray` closure.

**Comment by sebersole** [comment]
> Same thing with mavenCentralSync. If someone configures sync = true but configures no user/password, I think there should be an error.

I completely disagree here.  We publish our package as part of an organization and that organization has its OSSRH credentials on its profile.  Those are the values that should be used by the Bintray Maven Central sync stuff - and in fact when you do this from the UI that is exactly what happens if you do not specify any values here.

All that said, I'm not so sure that this is the same thing that happens from the plugin.  I do not specify the sync creds in the plugin config for the reasons I described above - but the sync does not automatically happen.  Does the plugin just ignore the `mavenCentralSync` section completely if no creds are given?  If so, it shouldn't.  It should just send the empty values.  I'll wait to open a new issue until its confirmed that this is what happens.

**Comment by AlexeiVainshtein** [comment]
Thank you for opening this issue @tomasbjerre . We are investigating this issue and how to improve this.

**Comment by AlexeiVainshtein** [comment]
Hi @tomasbjerre 

I just wanted to update you upon the release of the new version 1.8.1 of the Gradle Bintray Plugin. Previously, if username or password were missing, the bintrayUpload was skipped (as you encountered). With this version, if a username or password are missing, bintrayUpload will not be skipped but the upload will fail with a 401 error:

`> Could not publish 'null/maven/gradle.tests.pkg.name5/1528775107200': HTTP/1.1 401 Unauthorized [message:This resource requires authentication]
`

Please let us know if this suits your needs. 

Thanks,

**Comment by tomasbjerre** [comment]
Great thanks!
