### ISSUE TITLE
Upload task fails the first time

### ISSUE THREAD

**Issue by aalmiray** [bintray/gradle-bintray-plugin#30]
When invoking `:bintrayUpload` for the first time ever on a project, a new package is created but the task will fail immediately as it can't upload the artifacts. An exception appears on the console

```
Execution failed for task ':bintrayUpload'.
> groovyx.net.http.HttpResponseException: Forbidden
```

Calling `:bintrayUpload` a second time makes it work as the package is already created.

**Comment by jaredsburrows** [comment]
I am seeing this with version 1.6. What was the fix? Is it on Bintray's side again or the plugin?

**Comment by eyalbe4** [comment]
@jaredsburrows, let us check this issue and upstate with our findings.

**Comment by jaredsburrows** [comment]
@noamt @eyalbe4 It looks like I had the wrong `entitlement` id. Maybe we can update the error that is returned?

I recently removed a `package` from `bintray`, then remade it. The `entitlement-id` was removed from the `package`. Then I used my personal `user-api-key` instead of the `entitlement-id` and then I was able to publish. Could this edge case have caused this issue?

**Comment by eyalbe4** [comment]
Thanks for the update @jaredsburrows 
This could explain the Forbidden response you got.

**Comment by jaredsburrows** [comment]
@eyalbe4 Yes but if I intentionally change the user/pass, I would an "unauth" error. Thanks for the quick response. I'll continue to add more information if I have any.
