### ISSUE TITLE
Crashes with Gradle 2.4

### ISSUE THREAD

**Issue by gernotstarke** [bintray/gradle-bintray-plugin#73]
see issue on gradle-forum:
https://discuss.gradle.org/t/gradle-2-4-fails-with-failed-to-notify-build-listener-where-gradle-2-3-successfully-builds/9515

**Comment by eyalbe4** [comment]
René Groeschke from the core Gradle dev team managed to find the root cause of the issue and provided a workaround for it (thank you Rene!)
The details are available at:
https://discuss.gradle.org/t/gradle-2-4-fails-with-failed-to-notify-build-listener-where-gradle-2-3-successfully-builds/9515

I'm therefore closing this issue.
